<?php
/**
 * Created by PhpStorm.
 * User: LY
 * Date: 2017/10/18
 * Time: 10:42
 */

namespace app\admin\common;

use think\Controller;
use think\Session;

class Base extends Controller {
    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!Session::get("user_id") || !Session::get("user_name")){
            $this->redirect("admin/Login/login");
        }

        // if(time() - session('session_start_time') > config('session')['expire']) {
        //     Session::clear('admin360');
        //     $this->redirect('admin/Login/login');
        // }
    }
}